# Generated by Django 4.0.1 on 2022-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, default='John', max_length=100)),
                ('surname', models.CharField(blank=True, default='Doe', max_length=100)),
                ('knows_python', models.BooleanField(default=False)),
                ('likes_godot', models.BooleanField(default=False)),
                ('rate_interest', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
